setClass("Fitness",representation(x="numeric"))

setClass("Ackley",contains ="Fitness")
setClass("Rosenbrock",contains ="Fitness")
setClass("Griewankg",contains ="Fitness")
setClass("Rastrigin",contains ="Fitness")
setClass("Sphere",contains ="Fitness")
setClass("Water",contains ="Fitness")
setClass("Plateau",representation(length="numeric"),contains ="Fitness")

setClass("OneMax",contains ="Fitness")
setClass("Quadratic",contains ="Fitness")
setClass("F5Cuban1",contains ="Fitness")
setClass("Deceptive3",contains ="Fitness")
setClass("Mmdp",contains ="Fitness")
setClass("Trap5",contains ="Fitness")
setClass("OneEdge",contains ="Fitness")
setClass("F3Poly",contains ="Fitness")
setClass("F5Poly",contains ="Fitness")
setClass("IsoPeaks",contains ="Fitness")
setClass("F5Muhl",contains ="Fitness")
setClass("IntDeceptive",representation(k="numeric",card="numeric"),contains ="Fitness")

setClass("ShiftedSphere",contains ="Fitness") 
setClass("ShiftedSchwefelProblem1.2",contains ="Fitness")
setClass("ShiftedRotatedHighCondElliptic",contains ="Fitness")
setClass("ShiftedSchwefelProblem1.2Noise",contains ="Fitness")
setClass("SchwefelProblem2.6GOBounds",contains ="Fitness")
setClass("ShiftedRosenbrock",contains ="Fitness")
setClass("ShiftedRotatedGriewankWithoutBounds",contains ="Fitness")
setClass("ShiftedRotatedAckleyGOBounds",contains ="Fitness")
setClass("ShiftedRastrigin",contains ="Fitness")
setClass("ShiftedRotatedRastrigin",contains ="Fitness")
setClass("ShiftedRotatedWeierstrass",contains ="Fitness")
setClass("SchwefelsProblem2.13",contains ="Fitness") 
setClass("ShiftedExpandedGriewankplusRosenbrock",contains ="Fitness")
setClass("ShiftedRotatedExpandedScafferF6",contains ="Fitness")
setClass("HybridCompositionGO120",contains ="Fitness")
setClass("RotatedHybridCompositionGO120",contains ="Fitness")
setClass("RotatedHybridCompositionGO120Noise",contains ="Fitness") 
setClass("RotatedHybridCompositionGO10",contains ="Fitness") 
setClass("RotatedHybridCompositionNarrowBasin",contains ="Fitness") 
setClass("RotatedHybridCompositionGOBounds",contains ="Fitness") 
setClass("RotatedHybridCompositionGO360",contains ="Fitness") 
setClass("RotatedHybridCompositionHighCondNumMatrix",contains ="Fitness") 
setClass("NonContinuousRotatedHybridComposition",contains ="Fitness") 
setClass("RotatedHybridCompositionGO260",contains ="Fitness") 
setClass("RotatedHybridCompositioWithoutBounds",contains ="Fitness") 

setMethod("fitness","Ackley",fitness.Ackley)
setMethod("fitness","Rosenbrock",fitness.Rosenbrock )
setMethod("fitness","Griewankg",fitness.Griewankg )
setMethod("fitness","Rastrigin",fitness.Rastrigin)
setMethod("fitness","Sphere",fitness.Sphere)
setMethod("fitness","Water",fitness.Water)
setMethod("fitness","Plateau",fitness.Plateau)
setMethod("fitness","ShiftedRastrigin",fitness.ShiftedRastrigin)

setMethod("fitness","OneMax",fitness.OneMax)
setMethod("fitness","Quadratic",fitness.Quadratic)
setMethod("fitness","F5Cuban1",fitness.F5Cuban1)
setMethod("fitness","Deceptive3",fitness.Deceptive3)
setMethod("fitness","Mmdp",fitness.Mmdp)
setMethod("fitness","Trap5",fitness.Trap5)
setMethod("fitness","OneEdge", fitness.OneEdge)
setMethod("fitness","F3Poly", fitness.F3Poly)
setMethod("fitness","F5Poly", fitness.F5Poly)
setMethod("fitness","F5Muhl", fitness.F5Muhl)
setMethod("fitness","IsoPeaks", fitness.IsoPeaks)
setMethod("fitness","IntDeceptive",fitness.IntDeceptive)

setMethod("fitness","ShiftedSphere",fitness.ShiftedSphere)
setMethod("fitness","ShiftedSchwefelProblem1.2",fitness.ShiftedSchwefelProblem1.2)
setMethod("fitness","ShiftedRotatedHighCondElliptic",fitness.ShiftedRotatedHighCondElliptic)
setMethod("fitness","ShiftedSchwefelProblem1.2Noise",fitness.ShiftedSchwefelProblem1.2Noise)
setMethod("fitness","SchwefelProblem2.6GOBounds",fitness.SchwefelProblem2.6GOBounds)
setMethod("fitness","ShiftedRosenbrock",fitness.ShiftedRosenbrock)
setMethod("fitness","ShiftedRotatedGriewankWithoutBounds",fitness.ShiftedRotatedGriewankWithoutBounds)
setMethod("fitness","ShiftedRotatedAckleyGOBounds",fitness.ShiftedRotatedAckleyGOBounds)
setMethod("fitness","ShiftedRastrigin",fitness.ShiftedRastrigin)
setMethod("fitness","ShiftedRotatedRastrigin",fitness.ShiftedRotatedRastrigin)
setMethod("fitness","ShiftedRotatedWeierstrass",fitness.ShiftedRotatedWeierstrass)
setMethod("fitness","SchwefelsProblem2.13",fitness.SchwefelsProblem2.13)
setMethod("fitness","ShiftedExpandedGriewankplusRosenbrock",fitness.ShiftedExpandedGriewankplusRosenbrock)
setMethod("fitness","ShiftedRotatedExpandedScafferF6",fitness.ShiftedRotatedExpandedScafferF6)
setMethod("fitness","HybridCompositionGO120",fitness.HybridCompositionGO120)
setMethod("fitness","RotatedHybridCompositionGO120",fitness.RotatedHybridCompositionGO120)
setMethod("fitness","RotatedHybridCompositionGO120Noise",fitness.RotatedHybridCompositionGO120Noise)
setMethod("fitness","RotatedHybridCompositionGO10",fitness.RotatedHybridCompositionGO10)
setMethod("fitness","RotatedHybridCompositionNarrowBasin",fitness.RotatedHybridCompositionNarrowBasin)
setMethod("fitness","RotatedHybridCompositionGOBounds",fitness.RotatedHybridCompositionGOBounds)
setMethod("fitness","RotatedHybridCompositionGO360",fitness.RotatedHybridCompositionGO360)
setMethod("fitness","RotatedHybridCompositionHighCondNumMatrix",fitness.RotatedHybridCompositionHighCondNumMatrix)
setMethod("fitness","NonContinuousRotatedHybridComposition",fitness.NonContinuousRotatedHybridComposition)
setMethod("fitness","RotatedHybridCompositionGO260",fitness.RotatedHybridCompositionGO260)
setMethod("fitness","RotatedHybridCompositioWithoutBounds",fitness.RotatedHybridCompositioWithoutBounds)
